### ISSUE TITLE
Increase shared user storage

### ISSUE THREAD

**Issue by ctr26** [bioimagearchive/k8s-jupyterhub#11]
```
singleuser:
  storage:
    extraVolumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
    extraVolumeMounts:
      - name: shm-volume
        mountPath: /dev/shm
```
