### ISSUE TITLE
Mount BioStudies as shared folder

### ISSUE THREAD

**Issue by ctr26** [bioimagearchive/k8s-jupyterhub#2]
```
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-bs-ftp
      nfs:
        # URL for the NFS server
        server: ###.###.###.#### Change this!
        path: "/fg_biostudies/.adm/databases/prod/submission/ftp/"
  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "604800"
      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-bs-ftp
          mountPath: /var/nfs
          readOnly: true
```

Example pod for BioStudies

Use these settings: 

```
singleuser:
  storage:
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: jupyterhub-shared-volume
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/shared
```

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-storage.html
